// const chek = 25;
// const explan = ["강제 여행 가능(단, 특수상황 제외)","5분-수제 마사지","기타, 플룻 뭐 아무거나 하기","노래 한 곡 부르기(단, 8시 이전)","간식 사옴","좋은 말","절","손 하트","사랑합니다"]
// const gift = ["납치권", "마사지", "재롱잔치", "노래 한 곡", "간식사기", "덕담", "절", "하트", "사랑합니다"];
// const pbt = [0, (25000 + (1875*chek)), (75000 + (3750*chek)), (125000 + (3750*chek)) ,(200000+(5625*chek)), (300000+(7500*chek)), (400000+(7500*chek)), (400000+(7500*chek)) + Math.floor((1000000 - ((25000 + (1875*chek)) + (50000 + (3750*chek)) + (50000 + (3750*chek)) + (75000+(5625*chek)) + (100000+(7500*chek)) + (100000+(7500*chek)))) / 3), (400000+(7500*chek)) + (2 * Math.floor((1000000 - ((25000 + (1875*chek)) + (50000 + (3750*chek)) + (50000 + (3750*chek)) + (75000+(5625*chek)) + (100000+(7500*chek)) + (100000+(7500*chek)))) / 3)), 1000000 ];
// function a() {
//     let ranNum = Math.floor((Math.random() * 999999) + 1);
//     for (let i = 0; i < gift.length; i++) {
//         if(pbt[i] < ranNum){
//             if(ranNum <= pbt[i + 1]){
//                 return [gift[i], explan[i]];
//             }
//         }
//     }
// }
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());
// console.log(a());